### ISSUE TITLE
unknown error in date_original

### ISSUE THREAD

**Issue by jcgy** [hredestig/rosettR#2]
R version 3.2.3
Windows 7

When attempting to follow the vignette:

`makeReport(pathToExperiment, "overview", quiet=TRUE)`

produces the following error in the console window:

`Error in shell.exec(url) : problem in displaying 'overview.html'
In addition: Warning message:
In readLines(con) : incomplete final line found on 'overview.Rmd'
` 

The overview output folder is created, and if I navigate and open overview.html I get the following error message displayed in the browser window - with no graphs or plate images displayed on the page.

`## Error in date_original(file): unknown error in date_original`

**Comment by hredestig** [comment]
this should be fixed with  a6c16d5
